name: Publish Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm

      - run: npm ci
      - run: npm run build

      - uses: teunmooij/github-versioned-release@v1
        with:
          template: 'javascript-action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
